Add the ability to install on static / predefined hosts

diff --git a/romana-install/romana-setup b/romana-install/romana-setup
--- a/romana-install/romana-setup
+++ b/romana-install/romana-setup
@@ -22,7 +22,7 @@ usage() {
 	echo "       romana-setup <h|--help>"
 	echo ""
 	echo "Stack Name:  user-defined stack name (default: $USER)"
-	echo "Platforms:   aws (default), vagrant"
+	echo "Platforms:   aws (default), vagrant, static"
 	echo "Distro:      ubuntu (default), centos"
 	echo "Stack Types: devstack (default), kubernetes"
 	echo "Actions:     install (default), uninstall"
@@ -49,8 +49,9 @@ fi
 stack_name="$USER"
 distro="ubuntu"
 platform="aws"
+inventory=""
 stack_type="devstack"
-required=( ansible-playbook )
+required=( ansible ansible-playbook )
 
 # Process command-line options
 if (( $# > 0 )); then 
@@ -61,16 +62,8 @@ if (( $# > 0 )); then
 				exit 0
 				;;
 			-n|--name)
-				case "$2" in
-					[a-zA-Z][a-zA-Z0-9]*)
-						stack_name="$2"
-						shift 2
-						;;
-					*)
-						echo "Invalid stack name: '$2' (must start with a letter, and contain only letters and digits)"
-						exit 1
-						;;
-				esac
+				stack_name="$2"
+				shift 2
 				;;
 			-d|--distro)
 				case "$2" in
@@ -84,6 +77,10 @@ if (( $# > 0 )); then
 						;;
 				esac
 				;;
+			-i|--inventory)
+				inventory="$2"
+				shift 2
+				;;
 			-p|--platform)
 				case "$2" in
 					aws)
@@ -94,6 +91,10 @@ if (( $# > 0 )); then
 					vagrant)
 						platform="vagrant"
 						required+=( "vagrant" )
+						shift 2
+						;;
+					static)
+						platform="static"
 						shift 2
 						;;
 					*)
@@ -156,6 +157,36 @@ for i in "${required[@]}"; do
 	fi
 done
 
+# Validate the options / combinations
+# stack name is valid:
+case "$stack_name" in
+	[a-zA-Z][a-zA-Z0-9]*)
+		# OK
+		;;
+	*)
+		echo "Invalid stack name: '$stack_name' (must start with a letter, and contain only letters and digits)"
+		exit 1
+		;;
+esac
+# static hosts, inventory must be set
+if [[ $platform = "static" ]]; then
+	if ! [[ "$inventory" ]]; then
+		echo "Inventory must be provided when using static infrastructure."
+		exit 1
+	fi
+	if ! [[ -e "$inventory" ]]; then
+		echo "Inventory '$inventory' not found."
+		exit 1
+	fi
+fi
+# inventory must not be set if using other platforms
+if [[ $platform != "static" ]]; then
+	if [[ "$inventory" ]]; then
+		echo "Inventory must not be provided when using non-static infrastructure."
+		exit 1
+	fi
+fi
+
 stack_data_dir="stacks/${stack_name}_${platform}_${distro}_${stack_type}"
 mkdir -p "${stack_data_dir}"
 
@@ -168,13 +199,17 @@ if [[ "$platform" == "aws" ]] && [[ -r ~/.aws/ec2_keypair ]]; then
 		ansible_args+=( -e ec2_keypair="$ec2_keypair" )
 	fi
 fi
+# Add static inventory setting if platform is static
+if [[ "$platform" == "static" ]]; then
+	ansible_args+=( -e static_inventory="$inventory" )
+fi
 
 case "$platform" in
-	aws|vagrant)
+	aws|vagrant|static)
 		case "$action" in
 			install)
 				ansible-playbook "$@" "${ansible_args[@]}" -i localhost create_hosts.yml  || exit 1
-				ansible-playbook "$@" "${ansible_args[@]}" -i "${stack_data_dir}/inventory" post-create.yml &&
+				ansible-playbook "$@" "${ansible_args[@]}" -i "${stack_data_dir}/inventory" post-create.yml
 				hosts_ready=0
 				for ((i=0; i < 5; i++)); do
 					echo "Attempting to connect to hosts"
