Updated the check.

diff --git a/containerize/targets/services/run-romana-services b/containerize/targets/services/run-romana-services
--- a/containerize/targets/services/run-romana-services
+++ b/containerize/targets/services/run-romana-services
@@ -137,11 +137,11 @@ fi
 
 # Check that we can connect to the apiserver
 printf "Checking connection to kubernetes api-server..."
-if ! kubectl_output=$(kubectl --server="$api_server" version 2>&1 | grep -v "^Client Version:"); then
-	printf "error: %s\n" "$kubectl_output"
+if ! kubectl_output=$(kubectl --server="$api_server" version 2>&1); then
+	printf "error: %s\n" "$(grep -v "^Client Version:" <<< "$kubectl_output")"
 	exit 1
 fi
-printf "ok. %s\n" "$kubectl_output"
+printf "ok."
 
 valid_number() {
 	if (($# != 1)); then
