Simple kubectl run test.

diff --git a/test/kubernetes-cluster/kubectl-run b/test/kubernetes-cluster/kubectl-run
--- a/test/kubernetes-cluster/kubectl-run
+++ b/test/kubernetes-cluster/kubectl-run
@@ -31,15 +31,23 @@ if ! result=$(kubectl run "$@" 2>&1); then
 	log_verbose "$result"
 	exit 1
 fi
+log_verbose "kubectl run: $result"
+
+if ! result=$(kubectl get deployment "$1" -o name 2>&1); then
+	log_message "kubectl get deployment failed"
+	log_verbose "$result"
+	exit 1
+fi
+log_verbose "kubectl get deployment: $result"
 
 intervals=(1 1 2 5 8 15 15 15 15 15)
 status=unknown
 for i in "${intervals[@]}"; do
-	{ read -r replicas; read -r available; } < <(kubectl get "deployments/$1" -o json | jq '.status.replicas, .status.availableReplicas')
-	if [[ "$replicas" ]] && [[ "$available" ]]; then
+	{ read -r replicas; read -r available; } < <(kubectl get deployment "$1" -o json | jq '.spec.replicas, .status.availableReplicas')
+	if [[ "$replicas" ]] && ! [[ "$replicas" = "null" ]] && [[ "$available" ]] && ! [[ "$available" = "null" ]]; then
 		if (( replicas == available )); then
 			status="ok"
-			log_verbose "Deployment created successfully."
+			log_verbose "Deployment created successfully. $available / $replicas running."
 			break
 		fi
 		log_verbose "$available/$replicas ready"
