E2E test for kubernetes. Checks same things as demo script

diff --git a/test/kubernetes-cluster/tenant-frontend-backend b/test/kubernetes-cluster/tenant-frontend-backend
--- a/test/kubernetes-cluster/tenant-frontend-backend
+++ b/test/kubernetes-cluster/tenant-frontend-backend
@@ -56,7 +56,7 @@ defer kubectl delete namespace "$tenant_name"
 intervals=( 1 1 2 5 )
 found=0
 for i in "${intervals[@]}"; do
-	if [[ "$(romana tenant list -f json | jq --arg tenantName "$tenant_name" '.[] | select(.name==$tenantName)')" ]]; then
+	if [[ "$(romana tenant list -f json | jq --arg tenantName "$tenant_name" '.[] | select(.Name==$tenantName)')" ]]; then
 		found=1
 		break
 	fi
@@ -67,68 +67,103 @@ if ! (( found )); then
 	exit 1
 fi
 
-if ! kubectl run --namespace="$tenant_name" --image=nginx --labels="segment=backend" backend; then
-	log_message "Deployment creation problem (backend)"
-	exit 1
-fi
-defer kubectl --namespace="$tenant_name" delete deployment backend
-
-intervals=(1 1 2 5 8)
-backend_ready=0
-for i in "${intervals[@]}"; do
-	{ read -r replicas; read -r available; } < <(kubectl --namespace="$tenant_name" get deployment backend -o json | jq '.spec.replicas, .status.availableReplicas')
-	if [[ "$replicas" ]] && ! [[ "$replicas" = "null" ]] && [[ "$available" ]] && ! [[ "$available" = "null" ]]; then
-		if (( replicas == available )); then
-			backend_ready=1
-			break
-		fi
+create_deployment() {
+	if (( $# != 3 )); then
+		log_message "create_deployment usage error ($# != 3)"
+		return 1
 	fi
-	sleep "$i"
-done
-if ! (( backend_ready )); then
-	log_message "Deployment spinup problem (backend)"
-	exit 1
-fi
+	local name="$1"
+	local image="$2"
+	local segment="$3"
 
-if ! kubectl run --namespace="$tenant_name" --image=cirros --labels="segment=frontend" frontend -- /bin/sleep 18446744073709551615; then
-	log_message "Deployment creation problem (frontend)"
-	exit 1
-fi
-defer kubectl --namespace="$tenant_name" delete deployment frontend
-
-intervals=(1 1 2 5 8)
-frontend_ready=0
-for i in "${intervals[@]}"; do
-	{ read -r replicas; read -r available; } < <(kubectl --namespace="$tenant_name" get deployment frontend -o json | jq '.spec.replicas, .status.availableReplicas')
-	if [[ "$replicas" ]] && ! [[ "$replicas" = "null" ]] && [[ "$available" ]] && ! [[ "$available" = "null" ]]; then
-		if (( replicas == available )); then
-			frontend_ready=1
-			break
-		fi
+	if ! kubectl run --namespace="$tenant_name" --image="$image" --labels="segment=$segment" "$name"; then
+		log_message "Deployment creation problem ($name)"
+		return 1
 	fi
-	sleep "$i"
-done
-if ! (( frontend_ready )); then
-	log_message "Deployment spinup problem (frontend)"
+
+	local intervals=(1 1 2 5 8)
+	local ready=0
+	for i in "${intervals[@]}"; do
+		{ read -r replicas; read -r available; } < <(kubectl --namespace="$tenant_name" get deployment "$name" -o json | jq '.spec.replicas, .status.availableReplicas')
+			if [[ "$replicas" ]] && ! [[ "$replicas" = "null" ]] && [[ "$available" ]] && ! [[ "$available" = "null" ]]; then
+				if (( replicas == available )); then
+					ready=1
+					break
+				fi
+			fi
+			sleep "$i"
+		done
+		if ! (( ready )); then
+			log_message "Deployment spinup problem ($name)"
+			exit 1
+		fi
+}
+
+delete_deployment() {
+	if (( $# != 1 )); then
+		log_message "delete_deployment usage error ($# != 1)"
+		return 1
+	fi
+	local name="$1"
+	if ! kubectl --namespace="$tenant_name" delete deployment "$name"; then
+		return 1
+	fi
+}
+
+test_frontend_backend() {
+	if (( $# != 1 )); then
+		log_message "test_frontend_backend usage error ($# != 1)"
+		return 1
+	fi
+	local expected_result="$1"
+
+	# Create frontend and backend
+	if ! (create_deployment backend nginx backend && create_deployment frontend cirros frontend); then
+		return 1
+	fi
+
+	# Get the backend pod IP
+	backend_ip=$(kubectl --namespace="$tenant_name" get pods --selector="segment=backend" -o json | jq -r '.items[0].status.podIP')
+	if ! [[ "$backend_ip" ]] || [[ "$backend_ip" = "null" ]]; then
+		log_message "Failed to get backend IP"
+		return 1
+	fi
+
+	# Get the frontend pod name
+	frontend_podname=$(kubectl --namespace="$tenant_name" get pods --selector="segment=frontend" -o json | jq -r '.items[0].metadata.name')
+	if ! [[ "$frontend_podname" ]] || [[ "$frontend_podname" = "null" ]]; then
+		log_message "Failed to get frontend podname"
+		return 1
+	fi
+
+	if kubectl --namespace="$tenant_name" exec "$frontend_podname" -- curl -s "$backend_ip" --connect-timeout 3 2>/dev/null; then
+		result="connected"
+	else
+		result="failed"
+	fi
+
+	if ! (delete_deployment backend && delete_deployment frontend); then
+		return 1
+	fi
+	if [[ "$result" != "$expected_result" ]]; then
+		log_message "Result was $result, expected $expected_result"
+		return 1
+	fi
+}
+
+# Default allow policy, should be able to connect
+if ! test_frontend_backend "connected"; then
 	exit 1
 fi
 
-# Get the backend pod IP
-backend_ip=$(kubectl --namespace="$tenant_name" get pods --selector="segment=backend" -o json | jq -r '.items[0].status.podIP')
-if ! [[ "$backend_ip" ]] || [[ "$backend_ip" = "null" ]]; then
-	log_message "Failed to get backend IP"
+# Enable isolation
+if ! kubectl annotate --overwrite namespaces "$tenant_name" 'net.alpha.kubernetes.io/network-isolation=on'; then
+	log_message "Failed to annotate namespace"
 	exit 1
 fi
 
-# Get the frontend pod name
-frontend_podname=$(kubectl --namespace="$tenant_name" get pods --selector="segment=frontend" -o json | jq -r '.items[0].metadata.name')
-if ! [[ "$frontend_podname" ]] || [[ "$frontend_podname" = "null" ]]; then
-	log_message "Failed to get frontend podname"
-	exit 1
-fi
-
-if kubectl --namespace="$tenant_name" exec "$frontend_podname" -- curl -s "$backend_ip" --connect-timeout 3 2>/dev/null; then
-	log_message "Connected from frontend to backend (not expected)"
+# Isolation enabled, connection should fail
+if ! test_frontend_backend "failed"; then
 	exit 1
 fi
 
@@ -139,8 +174,6 @@ if ! curl -X POST -H 'Content-Type: application/json' -d @frontend-to-backend.js
 fi
 defer curl -X DELETE "$kube_apiserver/apis/romana.io/demo/v1/namespaces/$tenant_name/networkpolicys/pol1"
 
-# Expect the kube-exec-curl command to succeed this time
-if ! kubectl --namespace="$tenant_name" exec "$frontend_podname" -- curl -s "$backend_ip" --connect-timeout 3 2>/dev/null; then
-	log_message "Unable to connect from frontend to backend"
+if ! test_frontend_backend "connected"; then
 	exit 1
 fi
