Wrapper scripts. Use docker instead of kubectl to exec.

diff --git a/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl b/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
--- a/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
+++ b/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
@@ -11,9 +11,9 @@ fi
 if (( n > 1 )); then
 	echo "Multiple pods found for romana-etcd." >&2
 fi
-pod=$(jq -r '.items[0].metadata.name // empty' <<< "$result")
-if ! [[ "$pod" ]]; then
-	echo "Pod name for romana-etcd not found" >&2
+container=$(jq -r '.items[0].status.containerStatuses[0].containerID // empty' <<< "$result")
+if ! [[ "$container" ]]; then
+	echo "Container ID for romana-etcd not found" >&2
 	exit 1
 fi
-exec kubectl -n kube-system exec -it "$pod" -- etcdctl "$@"
+exec sudo docker exec -it "${container#docker://}" etcdctl "$@"
