Revert, but only apply `-t` when interactive

diff --git a/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl b/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
--- a/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
+++ b/romana-install/roles/stack/kubernetes/install-master/files/wrappers/etcdctl
@@ -11,9 +11,13 @@ fi
 if (( n > 1 )); then
 	echo "Multiple pods found for romana-etcd." >&2
 fi
-container=$(jq -r '.items[0].status.containerStatuses[0].containerID // empty' <<< "$result")
-if ! [[ "$container" ]]; then
-	echo "Container ID for romana-etcd not found" >&2
+pod=$(jq -r '.items[0].metadata.name // empty' <<< "$result")
+if ! [[ "$pod" ]]; then
+	echo "Pod name for romana-etcd not found" >&2
 	exit 1
 fi
-exec sudo docker exec -it "${container#docker://}" etcdctl "$@"
+exec_opt="-i"
+if [[ -t 1 ]]; then
+	exec_opt="-it"
+fi
+exec kubectl -n kube-system exec "$exec_opt" "$pod" -- etcdctl "$@"
