Install CNI before checking if etcd is ready.

diff --git a/containerize/targets/agent/run-romana-agent b/containerize/targets/agent/run-romana-agent
--- a/containerize/targets/agent/run-romana-agent
+++ b/containerize/targets/agent/run-romana-agent
@@ -113,24 +113,6 @@ else
 	usage_error "Romana etcd endpoints must be provided."
 fi
 
-# Check if etcd is running. Run check for cluster-health
-printf "Checking if etcd is running..."
-intervals=( 0 1 1 1 3 3 3 )
-etcd_ready=0
-for i in "${intervals[@]}"; do
-	sleep "$i"
-	if etcd_response=$(etcdctl --endpoints="$etcd_endpoints" cluster-health 2>/dev/null); then
-		etcd_ready=1
-		break
-	fi
-done
-if ! (( etcd_ready )); then
-	printf "error connecting to etcd: %s\n" "$etcd_response"
-	exit 1
-fi
-printf "ok.\n"
-printf "%s\n" "$etcd_response"
-
 # NODENAME environment variable must be set
 if ! [[ "$NODENAME" ]]; then
 	usage_error "Ensure NODENAME is specified in your daemonset for romana-agent"
@@ -329,6 +311,24 @@ if [[ -d /host/etc/romana ]]; then
 	)
 	sed "${replacements[@]}" /var/lib/romana/templates/dot-romana.template > /host/etc/romana/cli.yml
 fi
+
+# Check if etcd is running. Run check for cluster-health
+printf "Checking if etcd is running..."
+intervals=( 0 1 1 1 3 3 3 )
+etcd_ready=0
+for i in "${intervals[@]}"; do
+	sleep "$i"
+	if etcd_response=$(etcdctl --endpoints="$etcd_endpoints" cluster-health 2>/dev/null); then
+		etcd_ready=1
+		break
+	fi
+done
+if ! (( etcd_ready )); then
+	printf "error connecting to etcd: %s\n" "$etcd_response"
+	exit 1
+fi
+printf "ok.\n"
+printf "%s\n" "$etcd_response"
 
 
 if [[ "$nat_interface" ]]; then
